steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/toxindex/toxtransformer-pdaa:v16'
      - '-f'
      - 'Dockerfile.pdaa'
      - '--build-arg'
      - 'BUILD_DATE=$_BUILD_DATE'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/toxindex/toxtransformer-pdaa:v16'

substitutions:
  _BUILD_DATE: '${_BUILD_DATE}'

timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
